### ISSUE TITLE
过年抢票 12306 走起 | TEAPER

### ISSUE THREAD

**Issue by teaper** [teaper/hexoblog#28]
https://www.teaper.dev/2019/12/25/12306/ 

 与人为善是修养，独来独往是性格！

**Comment by VinceBlue** [comment]
当前ip: 112.123.33.18, 延时: 995.342
当前ip: 61.162.100.252, 延时: 996.582
当前ip: 218.60.185.46, 延时: 997.863
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "/usr/src/app/init/select_ticket_info.py", line 16, in <module>
    from init.login import GoLogin
  File "/usr/src/app/init/login.py", line 8, in <module>
    from inter.GetRandCode import getRandCode
  File "/usr/src/app/inter/GetRandCode.py", line 6, in <module>
    from verify.localVerifyCode import Verify
  File "/usr/src/app/verify/localVerifyCode.py", line 7, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

运行查看投票log后，加入CND后就出现了这种情况，请问是什么原因的，我在是12306文件夹运行的。
我也按照B站上你的视频操作了几次，也是如此。能给看看什么原因 吗？

**Comment by teaper** [comment]
> @VinceBlue
> 当前ip: 112.123.33.18, 延时: 995.342
> 当前ip: 61.162.100.252, 延时: 996.582
> 当前ip: 218.60.185.46, 延时: 997.863
> Traceback (most recent call last):
>   File "run.py", line 21, in <module>
>     from init import select_ticket_info
>   File "/usr/src/app/init/select_ticket_info.py", line 16, in <module>
>     from init.login import GoLogin
>   File "/usr/src/app/init/login.py", line 8, in <module>
>     from inter.GetRandCode import getRandCode
>   File "/usr/src/app/inter/GetRandCode.py", line 6, in <module>
>     from verify.localVerifyCode import Verify
>   File "/usr/src/app/verify/localVerifyCode.py", line 7, in <module>
>     import cv2
> ModuleNotFoundError: No module named 'cv2'
> 
> 运行查看投票log后，加入CND后就出现了这种情况，请问是什么原因的，我在是12306文件夹运行的。
> 我也按照B站上你的视频操作了几次，也是如此。能给看看什么原因 吗？
> 

可以参照[IOError: [Errno 0] Error看此issues #159](https://github.com/testerSunshine/12306/issues/159)，在 CMD 中使用 `chcp 65001` 命令，将页码格式 `936(GBK)` 改为 `UTF-8` 试试

**Comment by hao507** [comment]
> @teaper
> > @VinceBlue
> > 当前ip: 112.123.33.18, 延时: 995.342
> > 当前ip: 61.162.100.252, 延时: 996.582
> > 当前ip: 218.60.185.46, 延时: 997.863
> > Traceback (most recent call last):
> >   File "run.py", line 21, in <module>
> >     from init import select_ticket_info
> >   File "/usr/src/app/init/select_ticket_info.py", line 16, in <module>
> >     from init.login import GoLogin
> >   File "/usr/src/app/init/login.py", line 8, in <module>
> >     from inter.GetRandCode import getRandCode
> >   File "/usr/src/app/inter/GetRandCode.py", line 6, in <module>
> >     from verify.localVerifyCode import Verify
> >   File "/usr/src/app/verify/localVerifyCode.py", line 7, in <module>
> >     import cv2
> > ModuleNotFoundError: No module named 'cv2'
> > 
> > 运行查看投票log后，加入CND后就出现了这种情况，请问是什么原因的，我在是12306文件夹运行的。
> > 我也按照B站上你的视频操作了几次，也是如此。能给看看什么原因 吗？
> > 
> 
> 可以参照[IOError: [Errno 0] Error看此issues #159](https://github.com/testerSunshine/12306/issues/159)，在 CMD 中使用 `chcp 65001` 命令，将页码格式 `936(GBK)` 改为 `UTF-8` 试试

**是在ubuntu下执行chcp 65001吗？执行后提示"too few arguments"**

**Comment by hao507** [comment]
> 当前ip: 112.123.33.18, 延时: 995.342
> 当前ip: 61.162.100.252, 延时: 996.582
> 当前ip: 218.60.185.46, 延时: 997.863
> Traceback (most recent call last):
> File "run.py", line 21, in 
> from init import select_ticket_info
> File "/usr/src/app/init/select_ticket_info.py", line 16, in 
> from init.login import GoLogin
> File "/usr/src/app/init/login.py", line 8, in 
> from inter.GetRandCode import getRandCode
> File "/usr/src/app/inter/GetRandCode.py", line 6, in 
> from verify.localVerifyCode import Verify
> File "/usr/src/app/verify/localVerifyCode.py", line 7, in 
> import cv2
> ModuleNotFoundError: No module named 'cv2'
> 
> 运行查看投票log后，加入CND后就出现了这种情况，请问是什么原因的，我在是12306文件夹运行的。
> 我也按照B站上你的视频操作了几次，也是如此。能给看看什么原因 吗？

**兄弟，我也遇到了一样的问题，你搞定了没？**
